export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const FETCHING_DATA = "FETCHING_DATA"
export const TOGGLE_SMS = "TOGGLE_MODAL";
export const USERNAME_PASSWORD = "USERNAME_PASSWORD";
export const REFRESH_TOKEN = "REFRESH_TOKEN"
export const LIKE = "LIKE";